version: "3"

services:
  # 서비스 이름
#  spring:
#    container_name: spring
#    hostname: spring
#    # 실행되는 컨텍스트 및 도커파일 지정
#    build:
#      context: ../
#      dockerfile: "./docker/dockerfile/spring.dockerfile"
#    ports:
#      - "8080:8080"
#    restart: "always"
#    networks:
#      - backend

  mysql:
    container_name: mysql
    hostname: mysql
#    image : mysql
    build:
      context: ../
      dockerfile: "./docker/dockerfile/mysql.dockerfile"
    networks:
      - backend
    volumes:
      - ./volume/mysql:/var/lib/mysql
    env_file: ".env"
    ports:
      - "3307:3306"
  redis:
    image: redis
    networks:
      - backend
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq
    env_file: ".env"
    networks:
      - backend
    volumes:
      - /home/ubuntu/volume/mq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "61613:61613"
      - "15672:15672"

  openvidu:
    image: openvidu/openvidu-dev:2.28.0
    networks:
      - backend
    ports:
      - "4443:4443"
    env_file:
      - ".env"

  #
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - backend
    volumes:
      - /home/ubuntu/volume/data:/data
    env_file: ".env"
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    networks:
      - backend
    ports:
      - "8082:8081"
    env_file: ".env"
    depends_on:
      - mongo

# 브리지 네트워크는 도커가 제공하는 네트워크 드라이버 중 하나로, 가상
# 인터페이스를 통해 컨테이너들을 연결한다.
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.16.20.0/24"
          gateway: "172.16.20.1"